apiVersion: v1
kind: Pod
metadata:
  name: add-task-test-pod
  namespace: dev
spec:
  restartPolicy: Never
  containers:
    - name: add-task
      image: test32971.azurecr.io/add-task-image:v2
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"